### ISSUE TITLE
Create Recipe

### ISSUE THREAD

**Issue by hupling** [mobileappdevhm20/team-project-team_3#1]
The user can create recipes ( ingredient, description, photo, category, author, rates, level of difficult, time)

- [x] Implement Coroutines
- [x] Set up Observer
- [x] Add ingredients via dialog
- [x] Add steps
- [x] Add timers
- [x] Save the recipe to the local database
- [x] Adapt detail view design to mockup

**Comment by hupling** [comment]
Add timers and add pictures can be implemented later

**Comment by bremade** [comment]
David:
- [ ] Ingredients amount stuff
- [ ] Add imageurl and description to database

Jan:
- [ ] Detail view style overhaul
- [ ] Edit different steps
- [ ] Timer Intent
- [ ] Cardview of the steps

**Comment by matthinc** [comment]
Tests working, code-quality is fine. Looks good.
