### ISSUE TITLE
Detail  View Recipe

### ISSUE THREAD

**Issue by hupling** [mobileappdevhm20/team-project-team_3#14]
Detailed overview of specific recipe
- [x] Retrieve recipe data from the global database
- [x] Display the data in the given view

**Comment by hupling** [comment]
David:
- [ ] Ingredients amount stuff
- [ ] Add imageurl and description to database
Jan:
- [ ] Detail view style overhaul
- [ ] Edit different steps
- [ ] Timer Intent
- [ ] Cardview of the steps

**Comment by bremade** [comment]
Design will be overhauled in another ticket. The Rest LGTM
